"""add broker settings

Revision ID: 4ad90ad57b61
Revises: 
Create Date: 2026-06-20 14:03:07.694145

"""
from typing import Sequence, Union

from alembic import op # type: ignore
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad90ad57b61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_setting_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DISCONNECTED', 'CONNECTING', 'CONNECTED', 'ERROR', 'INACTIVE', name='brokerstatus'), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.Column('disconnected_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('connection_type', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['broker_setting_id'], ['broker_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('broker_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_setting_id', sa.Uuid(), nullable=False),
    sa.Column('broker_trade_id', sa.String(length=255), nullable=True),
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('is_martingale', sa.Boolean(), nullable=False),
    sa.Column('cycle_step', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['broker_setting_id'], ['broker_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # CORREÇÃO PARA O SQLITE: Colunas alteradas para nullable=True ou adicionado server_default
    op.add_column('broker_settings', sa.Column('broker_type', sa.Enum('IQOPTION', 'QUOTEX', 'POCKETOPTION', name='brokertype'), nullable=True))
    op.add_column('broker_settings', sa.Column('is_primary', sa.Boolean(), nullable=True, server_default='0'))
    op.add_column('broker_settings', sa.Column('status', sa.Enum('DISCONNECTED', 'CONNECTING', 'CONNECTED', 'ERROR', 'INACTIVE', name='brokerstatus'), nullable=True))
    op.add_column('broker_settings', sa.Column('last_connected', sa.DateTime(), nullable=True))
    op.add_column('broker_settings', sa.Column('last_heartbeat', sa.DateTime(), nullable=True))
    op.add_column('broker_settings', sa.Column('connection_error', sa.Text(), nullable=True))
    op.add_column('broker_settings', sa.Column('iq_email', sa.String(length=255), nullable=True))
    op.add_column('broker_settings', sa.Column('iq_password', sa.String(length=255), nullable=True))
    op.add_column('broker_settings', sa.Column('iq_user_id', sa.Integer(), nullable=True))
    op.add_column('broker_settings', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('broker_settings', sa.Column('quotex_username', sa.String(length=255), nullable=True))
    op.add_column('broker_settings', sa.Column('quotex_api_key', sa.String(length=500), nullable=True))
    op.add_column('broker_settings', sa.Column('po_username', sa.String(length=255), nullable=True))
    op.add_column('broker_settings', sa.Column('po_api_key', sa.String(length=500), nullable=True))
    op.add_column('broker_settings', sa.Column('default_stake', sa.Float(), nullable=True))
    op.add_column('broker_settings', sa.Column('max_stake', sa.Float(), nullable=True))
    op.add_column('broker_settings', sa.Column('max_gales', sa.Integer(), nullable=True))
    op.add_column('broker_settings', sa.Column('daily_stop_loss', sa.Float(), nullable=True))
    op.add_column('broker_settings', sa.Column('daily_meta', sa.Float(), nullable=True))
    op.add_column('broker_settings', sa.Column('max_cycle_pct', sa.Float(), nullable=True))
    op.add_column('broker_settings', sa.Column('latency_protection', sa.Boolean(), nullable=True, server_default='1'))
    op.add_column('broker_settings', sa.Column('auto_stop_on_loss', sa.Boolean(), nullable=True, server_default='0'))
    op.add_column('broker_settings', sa.Column('balance', sa.Float(), nullable=True))
    op.add_column('broker_settings', sa.Column('balance_updated_at', sa.DateTime(), nullable=True))
    op.add_column('broker_settings', sa.Column('total_trades', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('broker_settings', sa.Column('total_wins', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('broker_settings', sa.Column('total_losses', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('broker_settings', sa.Column('total_profit', sa.Float(), nullable=True, server_default='0.0'))
    op.add_column('broker_settings', sa.Column('today_trades', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('broker_settings', sa.Column('today_profit', sa.Float(), nullable=True, server_default='0.0'))
    op.add_column('broker_settings', sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')))
    op.add_column('broker_settings', sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')))
    op.add_column('broker_settings', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('broker_settings', sa.Column('admin_notes', sa.Text(), nullable=True))
    
    # Modo batch para permitir alteração de colunas e constraints que o SQLite nativo bloqueia
    with op.batch_alter_table('broker_settings', schema=None) as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   type_=sa.Uuid(),
                   existing_nullable=False)
        batch_op.alter_column('api_token',
                   existing_type=sa.VARCHAR(length=512),
                   type_=sa.String(length=500),
                   existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_broker_settings_broker_type'), ['broker_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_broker_settings_status'), ['status'], unique=False)
        batch_op.create_foreign_key('fk_broker_settings_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('email')
        batch_op.drop_column('is_demo')
        batch_op.drop_column('password')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broker_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=512), nullable=True))
        batch_op.add_column(sa.Column('is_demo', sa.BOOLEAN(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('fk_broker_settings_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_broker_settings_status'))
        batch_op.drop_index(batch_op.f('ix_broker_settings_broker_type'))
        batch_op.alter_column('api_token',
                   existing_type=sa.String(length=500),
                   type_=sa.VARCHAR(length=512),
                   existing_nullable=True)
        batch_op.alter_column('id',
                   existing_type=sa.Uuid(),
                   type_=sa.INTEGER(),
                   existing_nullable=False)
        batch_op.drop_column('admin_notes')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('today_profit')
        batch_op.drop_column('today_trades')
        batch_op.drop_column('total_profit')
        batch_op.drop_column('total_losses')
        batch_op.drop_column('total_wins')
        batch_op.drop_column('total_trades')
        batch_op.drop_column('balance_updated_at')
        batch_op.drop_column('balance')
        batch_op.drop_column('auto_stop_on_loss')
        batch_op.drop_column('latency_protection')
        batch_op.drop_column('max_cycle_pct')
        batch_op.drop_column('daily_meta')
        batch_op.drop_column('daily_stop_loss')
        batch_op.drop_column('max_gales')
        batch_op.drop_column('max_stake')
        batch_op.drop_column('default_stake')
        batch_op.drop_column('po_api_key')
        batch_op.drop_column('po_username')
        batch_op.drop_column('quotex_api_key')
        batch_op.drop_column('quotex_username')
        batch_op.drop_column('iq_user_id')
        batch_op.drop_column('iq_password')
        batch_op.drop_column('iq_email')
        batch_op.drop_column('connection_error')
        batch_op.drop_column('last_heartbeat')
        batch_op.drop_column('last_connected')
        batch_op.drop_column('status')
        batch_op.drop_column('is_primary')
        batch_op.drop_column('broker_type')

    op.drop_table('broker_trades')
    op.drop_table('broker_connections')
    # ### end Alembic commands ###
    