"""create users table

Revision ID: f5f894a3114f
Revises: 4ad90ad57b61
Create Date: 2026-06-24 12:36:00.323742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f894a3114f'
down_revision: Union[str, Sequence[str], None] = '4ad90ad57b61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_email', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_user', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('max_signals_per_day', sa.Integer(), nullable=False),
    sa.Column('max_stake', sa.Float(), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('plan_expires_at', sa.DateTime(), nullable=True),
    sa.Column('broker', sa.String(length=50), nullable=True),
    sa.Column('api_token', sa.String(length=255), nullable=True),
    sa.Column('iq_email', sa.String(length=255), nullable=True),
    sa.Column('iq_password', sa.String(length=255), nullable=True),
    sa.Column('stake', sa.Float(), nullable=False),
    sa.Column('max_gales', sa.Integer(), nullable=False),
    sa.Column('risk_mode', sa.String(length=20), nullable=False),
    sa.Column('total_profit', sa.Float(), nullable=False),
    sa.Column('daily_stop_loss', sa.Float(), nullable=False),
    sa.Column('daily_meta', sa.Float(), nullable=False),
    sa.Column('current_cycle_step', sa.Integer(), nullable=False),
    sa.Column('cycle_step', sa.Integer(), nullable=False),
    sa.Column('max_cycle_pct', sa.Float(), nullable=False),
    sa.Column('is_in_cycle', sa.Boolean(), nullable=False),
    sa.Column('stop_loss_pct', sa.Float(), nullable=True),
    sa.Column('daily_meta_pct', sa.Float(), nullable=True),
    sa.Column('telegram_enabled', sa.Boolean(), nullable=False),
    sa.Column('latency_protection', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active_trading', sa.Boolean(), nullable=False),
    sa.Column('trading_enabled', sa.Boolean(), nullable=False),
    sa.Column('liberado', sa.Boolean(), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('broker_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('broker_type', sa.Enum('IQOPTION', 'QUOTEX', 'POCKETOPTION', name='brokertype'), nullable=False),
    sa.Column('broker_name', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DISCONNECTED', 'CONNECTING', 'CONNECTED', 'ERROR', 'INACTIVE', name='brokerstatus'), nullable=False),
    sa.Column('last_connected', sa.DateTime(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('connection_error', sa.Text(), nullable=True),
    sa.Column('api_token', sa.String(length=500), nullable=True),
    sa.Column('iq_email', sa.String(length=255), nullable=True),
    sa.Column('iq_password', sa.String(length=255), nullable=True),
    sa.Column('iq_user_id', sa.Integer(), nullable=True),
    sa.Column('quotex_username', sa.String(length=255), nullable=True),
    sa.Column('quotex_api_key', sa.String(length=500), nullable=True),
    sa.Column('po_username', sa.String(length=255), nullable=True),
    sa.Column('po_api_key', sa.String(length=500), nullable=True),
    sa.Column('default_stake', sa.Float(), nullable=True),
    sa.Column('max_stake', sa.Float(), nullable=True),
    sa.Column('max_gales', sa.Integer(), nullable=True),
    sa.Column('daily_stop_loss', sa.Float(), nullable=True),
    sa.Column('daily_meta', sa.Float(), nullable=True),
    sa.Column('max_cycle_pct', sa.Float(), nullable=True),
    sa.Column('latency_protection', sa.Boolean(), nullable=False),
    sa.Column('auto_stop_on_loss', sa.Boolean(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('balance_updated_at', sa.DateTime(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('total_wins', sa.Integer(), nullable=False),
    sa.Column('total_losses', sa.Integer(), nullable=False),
    sa.Column('total_profit', sa.Float(), nullable=False),
    sa.Column('today_trades', sa.Integer(), nullable=False),
    sa.Column('today_profit', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broker_settings_broker_type'), 'broker_settings', ['broker_type'], unique=False)
    op.create_index(op.f('ix_broker_settings_status'), 'broker_settings', ['status'], unique=False)
    op.create_table('plan_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('old_plan', sa.String(length=50), nullable=True),
    sa.Column('new_plan', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.String(length=255), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('broker_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_setting_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DISCONNECTED', 'CONNECTING', 'CONNECTED', 'ERROR', 'INACTIVE', name='brokerstatus'), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.Column('disconnected_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('connection_type', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['broker_setting_id'], ['broker_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('broker_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_setting_id', sa.Uuid(), nullable=False),
    sa.Column('broker_trade_id', sa.String(length=255), nullable=True),
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('is_martingale', sa.Boolean(), nullable=False),
    sa.Column('cycle_step', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['broker_setting_id'], ['broker_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('broker_trades')
    op.drop_table('broker_connections')
    op.drop_table('signal_usage')
    op.drop_table('plan_history')
    op.drop_index(op.f('ix_broker_settings_status'), table_name='broker_settings')
    op.drop_index(op.f('ix_broker_settings_broker_type'), table_name='broker_settings')
    op.drop_table('broker_settings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('plans')
    op.drop_table('admin_logs')
    # ### end Alembic commands ###
