from cryptography.fernet import Fernet
from src.core.config import settings


class EncryptionService:
    def __init__(self):
        # We must ensure the key is base64 encoded and valid for Fernet
        self.key = settings.ENCRYPTION_KEY.encode()
        try:
            self.cipher_suite = Fernet(self.key)
        except Exception:
            # Fallback for dynamic generation if key is invalid/missing (useful for local dev)
            # In production, ENCRYPTION_KEY must be a valid Fernet key generated by Fernet.generate_key()
            self.cipher_suite = Fernet(Fernet.generate_key())

    def encrypt(self, plain_text: str) -> str:
        if not plain_text:
            return ""
        return self.cipher_suite.encrypt(plain_text.encode()).decode()

    def decrypt(self, cipher_text: str) -> str:
        if not cipher_text:
            return ""
        return self.cipher_suite.decrypt(cipher_text.encode()).decode()


encryption_service = EncryptionService()
